project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - slides.qmd
        
website:
  title: ""
  search: false

  navbar:
    search: false
    link-external-newwindow: true
    title: BUSI 721
    right:

      - text: Code Binder
        href: https://mybinder.org/v2/gh/kerryback/2023-721-901-binder.git/HEAD

      - text: Slide Decks
        file: slides.qmd

      - text: BBCX Investments Library
        href: https://bbcx-investments.com

      - text: Investments Notes
        href: http://notes.kerryback.com
        
      - text: Home
        file: index.qmd


         
format: 
  html:
    theme: cosmo
    scss: styles.css
    link-external-newwindow: true
    



